#import = [ "~/.config/alacritty/alacritty-theme/themes/afterglow.toml" ]

[env]
TERM="xterm-256color"

[window]
dynamic_title = true
title = "Alacritty"
startup_mode = "Maximized"

[mouse]
hide_when_typing = false

[colors.primary]
background = '#0a0a0a'

[font]
size = 15

[font.bold]
family = "Lilex Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Lilex Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Lilex Nerd Font"
style = "Italic"

[font.normal]
family = "Lilex Nerd Font"

[[keyboard.bindings]]
key = "Home"
chars = "\u001b[H"

# Move to the end of the line
[[keyboard.bindings]]
key = "End"
chars = "\u001b[F"

# Move one word left
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

# Move one word right
[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"
